Netflix import cleanup
leepeuker/movary pull request #256
Opened 2023-01-28 19:52 UTC by leepeuker

2023-01-28 19:54 UTC, leepeuker commented
@JVT038 In case your interested, I will do my refactoring/improvements on the Netflix import here

2023-01-28 20:21 UTC, JVT038 requested changes

2023-01-28 20:21 UTC, JVT038 commented on src/HttpController/NetflixController.php
>       */
Why have you removed these things?
I personally find them very useful, as they provide the necessary information for my IDE to properly show and describe a function.

2023-01-28 20:21 UTC, JVT038 commented on src/HttpController/NetflixController.php
> -        // https://www.php.net/manual/en/function.finfo-open.php
BTW, do you think simply checking the file extension is sufficient to verify that it's actually a CSV file?
Or would you rather use the Magic module, that actually inspects the file data itself and can check the MIME type very accurately?

2023-01-28 20:28 UTC, JVT038 commented on src/HttpController/NetflixController.php
>       */
Why have you removed these things?
I personally find them very useful, as they provide the necessary information for my IDE to properly show and describe a function.
They can additionally be useful for other developers who want to contribute. 
Adding comments like these can be really useful and helps to describe a method / function.

2023-01-28 20:28 UTC, JVT038 commented on src/HttpController/NetflixController.php
> -        // https://www.php.net/manual/en/function.finfo-open.php
BTW, do you think simply checking the file extension is sufficient to verify that it's actually a CSV file?
Or would you rather use the Magic module, that actually inspects the file data itself and can check the MIME type very accurately?

2023-01-29 10:22 UTC, leepeuker commented on src/HttpController/NetflixController.php
>       */
Probably because of habit, I am not a friend of comments most of the time. These docblock comments do not provide much useful information you cannot (or should be able to) get from the methods signature itself and can be downright wrong if not maintained well (code changed but comments did not and things like that).

For example:

> @param Request $request the CSV file containing the Netflix data

The type should be clear by the methods signature and what the parameter contain can be made clear through naming (class name is `NetflixController` and parameter `Request $csvImportRequest`).

> @return Response HTTP response with either an error code or JSON object containing the TMDB results

Same here, return type is defined via methods signature. That a http response can have an error code should be clear by the nature of http responses and that the successfully response can be made clear through method naming, e.g. `provideTmdbMatchesForNetflixCsv`.  

In my experience comments lead developers to be lazy, why find good namings and improve code readability when you can write a comment to explain an unreadable mess, at least that is what comments are inherently are supporting even if you do not want it.

This does not count for all comments and all situations of course. There are totally valid comments explaining difficult code or giving a high level overview about an entry method to a complex process and you are of course correct that it can be useful for contributors, but to be honest right now I would prefer less contributors than to work with docblocks causing the issues I see mentioned at the beginning.

2023-01-29 10:33 UTC, leepeuker commented on src/HttpController/NetflixController.php
> -        // https://www.php.net/manual/en/function.finfo-open.php
Yeah I think it is fine, I see no reason to be super correct here, I not think it should impact usability or open us to any attack vectors.

2023-01-29 11:55 UTC, JVT038 commented on src/HttpController/NetflixController.php
>       */
I get your point, however the parameters occasionally require a comprehensive and detailed description, which can't be put in the naming. Or you would get absurdly long variable names, but that would decrease readability.

And I also just think it looks cool for my IDE, but this argument is probably just a big fallacy, hahaha.

Anyway, I'll keep this in mind and remove the `@return` and `@param` tags then. I'll probably keep the description and summaries in the docbloc.

2023-01-29 11:56 UTC, JVT038 approved these changes

2023-01-29 11:56 UTC, JVT038 commented on src/HttpController/NetflixController.php
> -        // https://www.php.net/manual/en/function.finfo-open.php
Yeah, you're right; the code only tries to read the file data and if it isn't a CSV, it'll probably throw an error.

2023-01-29 13:29 UTC, leepeuker commented on src/HttpController/NetflixController.php
>       */
> however the parameters occasionally require a comprehensive and detailed description, which can't be put in the naming. Or you would get absurdly long variable names, but that would decrease readability

Then I have no issue with a comment

> And I also just think it looks cool for my IDE, but this argument is probably just a big fallacy, hahaha.

No I totally get you :D 

You can definitely keep comments you find necessary because you cannot express this information via code, I have no issue with that. Just keep in mind comments could/should be removed when the code was for example refactored to be better understandable (hopefully :see_no_evil: ).

2023-01-29 14:52 UTC, JVT038 reviewed
Why have you moved the logic to `ValueObject`?
What should `ValueObject` even contain?

2023-01-29 15:05 UTC, leepeuker commented
> Why have you moved the logic to `ValueObject`? What should `ValueObject` even contain?

I have renamed the namespace to `Dto`, these classes are not value objects (if you want to know more about value objects I can recommend to read [this](https://martinfowler.com/bliki/ValueObject.html)).

I do not like to pass arrays around between classes. Arrays are inherently type unsafe because of their dynamic nature and difficult to maintain (e.g. when the structure changes you have a lot of manual work to do for fixing all usages, that is much easier having an object woth getter methods for the data).

2023-01-29 15:49 UTC, leepeuker commented on README.md
> +* [@JVT038](https://github.com/JVT038) as JVT038
@JVT038 If you do not want to mentioned I can remove this

2023-01-29 15:54 UTC, leepeuker commented
@JVT038 So, I think I am done here. Please test it again to make sure I broke nothing, it seems good to me. Checkout the first comment of the PR to see what I changed besides the refactoring.

The only issue I see is that we should maybe change the actual import to be processed as a background job and not during the http request to prevent issues like timeouts. I have tested a import with ~300 movies and it went reasonable well. Not sure about bigger histories

2023-01-29 16:07 UTC, merged

2023-01-29 16:08 UTC, leepeuker commented
I have removed merged only the refactoring and changes I mentioned at the top. We have to fix https://github.com/leepeuker/movary/issues/259 before making it officially available